### ISSUE TITLE
how do i open the gui

### ISSUE THREAD

**Issue by master7720** [HausemasterIssue/ICEHack-b1-SRC#1]

**Comment by HausemasterIssue** [comment]
you shouldn't be even using this client, it's old and could be a rat idfk.

try finding the prefix, like do all the usual prefix keys till u get a response, then do something like .bind clickgui p or .bind gui p or just try pressing keys, the usual ones are, o, p, rshift, r, y, etc.

**Comment by master7720** [comment]
owning cc rn with it
